### ISSUE TITLE
Exe File

### ISSUE THREAD

**Issue by Paptoos** [alirezaahani/Phonebook#1]
I don't work with pyqt and i work with tkinter but you can create exe file from any python programm using pyinstaller
if you use pyinstaller user don't need install python and pyqt

**Comment by alirezaahani** [comment]
I know, I tried on Wine but the EXE file is huge!! 35MB.
But I will add binary files for Windows and Linux.
Thanks for your great suggestion.

**Comment by Paptoos** [comment]
You are welcome
